### ISSUE TITLE
Settings failing to save

### ISSUE THREAD

**Issue by QuarTheDev** [nymda/knedmod#5]
When modifying the settings in the F1 menu, exiting and re-entering the game causes the game to not remember what those settings were. It's unclear to me if this was intended or not. If this wasn't intended behaviour, you can create a small file inside the game directory (a config file) where you can 'save' the settings and read from them upon startup, and also have the ability to tweak those settings directly from the file, even without being in the game. 

Here's a nice article to help assist me in what I'm trying to explain:
[https://en.wikipedia.org/wiki/Configuration_file](https://en.wikipedia.org/wiki/Configuration_file)

**Comment by nymda** [comment]
Currently this isnt implemented as the settings are fairly simple so i didnt think it was necessary, however i may add it at some point
